# This is an example configuration to enable detect-secrets in the pre-commit hook.
# Add this file to the root folder of your repository.
#
# Read pre-commit hook framework https://pre-commit.com/ for more details about the structure of config yaml file and how git pre-commit would invoke each hook.
#
# This line indicates we will use the hook from ibm/detect-secrets to run scan during committing phase.
repos:
  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.61.dss
    hooks:
      - id: detect-secrets # pragma: whitelist secret
        args: [--baseline, .secrets.baseline, --use-all-plugins]
        exclude: 'src/fp_helper/_vendor/.*'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        exclude: 'src/fp_helper/_vendor/.*'
      # Run the formatter.
      - id: ruff-format
        exclude: 'src/fp_helper/_vendor/.*'

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        exclude: 'src/fp_helper/_vendor/.*'

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        types_or: [python, rst, markdown, cython, c]
        additional_dependencies: [tomli]
        exclude: 'src/fp_helper/_vendor/.*'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        # exclude: |
        #   (?x)^(

        #   )$
      - id: trailing-whitespace
